# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

container:
  image: mcr.microsoft.com/dotnet/core/sdk:2.2.203-alpine3.9

variables:
  buildConfiguration: 'Release'

steps:
- script: echo buildConfiguration $(buildConfiguration)

#steps:
#- script: dotnet build --configuration $(buildConfiguration)
#  displayName: 'dotnet build $(buildConfiguration)'
